### ISSUE TITLE
Please define external collaborators in code

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/bai2#21]
Hi there

We now have a process to manage github collaborators in code:
https://github.com/ministryofjustice/github-collaborators/blob/main/README.md#github-external-collaborators

Please follow the procedure described there to grant @ibrechin access to this repository.

If you have any questions, please post in #ask-operations-engineering on Slack.

**Comment by ushkarev** [comment]
Oops sorry for forgetting the protocol!
https://github.com/ministryofjustice/github-collaborators/pull/91
