### ISSUE TITLE
Please define outside collaborators in code

### ISSUE THREAD

**Issue by NickWalt01** [ministryofjustice/bai2#35]
Hi there

We have a process to manage github collaborators in code: https://github.com/ministryofjustice/github-collaborators

Please follow the procedure described there to grant @ibrechin access to this repository.

If you have any questions, please post in #ask-operations-engineering on Slack.

If the outside collaborator is not needed, close this issue, they have already been removed from this repository.

**Comment by ushkarev** [comment]
@NickWalt01 he's already listed there:
https://github.com/ministryofjustice/github-collaborators/blob/main/terraform/bai2.tf
as it's not expired yet, is there anything you still want me to do?

**Comment by NickWalt01** [comment]
Hi @ushkarev there was an error in our automation, this was a mistake, I'll have a fix out shortly, then run Terraform apply again to get the re-invites sent out to Ibrechin, sorry about this

**Comment by NickWalt01** [comment]
Automation error: adding user back in manually

**Comment by ushkarev** [comment]
Thanks Nick! It's unfortunate that their access isn't automatically restored but requires an invitation :(

**Comment by NickWalt01** [comment]
True, I thought it would have just added them back in, sorry for the inconvenience
