### ISSUE TITLE
Open to supporting Python 2.7?

### ISSUE THREAD

**Issue by chazeah** [ministryofjustice/bai2#5]
Hey there,

We're receiving about 150 BAI files/day right now and would love to use this library. Our entire codebase is Python 2.7, though. We've experimented with making your library 2.7-compatible and it's pretty straightforward. If we put out a PR for these changes, would you accept it? And going forward, would you be willing to develop in a 2.7-compatible way? Again, it's not very different than what you've got now.

Thanks,
Charley

**Comment by ibrechin** [comment]
Hi,

It's great to hear that you might find this library useful. We would certainly welcome contributions for 2.7 compatibility, and would be willing to maintain this compatibility in any future development. Just raise a PR and we'll give it a look.

Cheers,
Ian

**Comment by chazeah** [comment]
Great! Within the next few weeks we plan on tackling this and will put out a PR. Thanks!
