### ISSUE TITLE
Parser does not handle `FundsType` code `Z`

### ISSUE THREAD

**Issue by davidthornton** [ministryofjustice/bai2#7]
On page 30 of the BAI2 file format specification ([BAI2 Files](http://www.bai.org/Libraries/Site-General-Downloads/Cash_Management_2005.sflb.ashx)) there is a "Funds Type" field which can take the value of `Z`, indicating that the type of funds specified by the transaction is "unknown".

Currently, the parser raises a `ValueError` when it encounters this value:

```
ValueError: Z is not a valid FundsType
```

The fix seems to be relatively simple (addition of that value to the `FundsType` `Enum` with an associated regression test).

**Comment by ushkarev** [comment]
should be resolved now
